apiVersion: skaffold/v1 # 	version of the configuration.
kind: Config # 	always Config.
metadata: # 	holds additional information about the config.
  name: homepage-antoine
build:
  artifacts:
    - image: gcr.io/homepage-antoine/web
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
